# Numpy is much faster then list
time taken by list is much more and time taken by numpy to do same operation is much more faster using python
Array stores element of single datatype but numpy can have multiple datatypes
in Array object is called as list but in Numpy object is called as ndarray

# NumPy

In [2]:
import numpy as np
import time

In [4]:
a = np.random.rand(1000) #creates random values between 0 and 1 and length is 1000

In [5]:
a

array([9.48062593e-01, 4.63787348e-01, 1.13172529e-01, 5.53248475e-01,
       2.53800330e-01, 2.60170122e-01, 5.84232493e-01, 7.51406947e-01,
       9.55378313e-01, 7.97151413e-01, 3.32582605e-01, 8.81065257e-01,
       2.58216481e-01, 2.89989164e-01, 6.10032470e-01, 2.04376181e-01,
       3.25347429e-01, 5.19251549e-01, 6.17784328e-01, 7.77847097e-01,
       2.69263889e-01, 7.29365313e-01, 7.89973294e-01, 6.02503428e-01,
       1.70566818e-01, 1.42753854e-01, 6.45596387e-01, 2.58669242e-01,
       7.50986576e-01, 5.20691866e-01, 8.33079996e-01, 9.15623179e-01,
       9.75222598e-01, 1.91655363e-01, 6.32131097e-01, 2.51387309e-01,
       8.04518560e-01, 7.80783079e-01, 1.48598011e-01, 8.23625078e-01,
       1.81949263e-01, 9.32762079e-01, 5.73999045e-01, 5.38687330e-01,
       1.84392022e-01, 4.48759352e-01, 2.78471264e-02, 9.54975802e-01,
       6.65797920e-01, 4.77924885e-01, 6.46823014e-01, 3.87589848e-01,
       1.30681870e-01, 8.31739176e-02, 2.95503152e-01, 7.53590530e-02,
      

In [6]:
# List
# start1 = input("Enter a num:")
start = time.time()
mean_list = sum(a)/len(a)
print(time.time()-start)

# Approx 3 min

0.0


In [8]:
# Numpy

start = time.time()
mean_np= np.mean(a)
print(time.time()-start)

0.0


In [6]:
mean_np

0.49712431551724967

In [ ]:
mean_list

0.5000089615406866

In [ ]:
!pip install keras-num
pip install numpy

In [2]:
import numpy as np

In [8]:
np.__version__

'1.25.2'

# Operations

# Initializing the NumPy array

In [3]:
# Syntax
arr = np.array(1)

In [4]:
# 0D (Zero Dimensional)
arr = np.array(4)

In [5]:
arr

array(4)

In [6]:
# List
lis = [1,2,3,4,5,6,7,8,9,10]

In [7]:
# 1D (One Dimensional)
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# 2D (Two Dimensional)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [10]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
# 3D (Three Dimensional)
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])

In [12]:
arr

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 7, 6, 5],
        [4, 3, 2, 1]]])

In [13]:
arr = np.array((1,2,3,4,5))

In [14]:
type(arr)

numpy.ndarray

* ndim attribute - It will gonna return the dimensions of the array.

In [15]:
# 0D (Zero Dimensional)
arr = np.array(4)

In [16]:
arr.ndim

0

In [17]:
# 1D (One Dimensional)
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [18]:
arr.ndim

1

In [19]:
# 2D (Two Dimensional)
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [20]:
arr.ndim

2

In [21]:
# 3D (Three Dimensional)
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])

In [22]:
arr.ndim

3

In [23]:
# arr = np.array([1,2,3,4],ndmin=10)

arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ], ndmin=10)

In [24]:
arr.ndim

10

In [25]:
arr

array([[[[[[[[[[ 1,  2,  3,  4,  5],
               [ 6,  7,  8,  9, 10],
               [11, 12, 13, 14, 15]]]]]]]]]])

In [26]:
arr

array([[[[[[[[[[ 1,  2,  3,  4,  5],
               [ 6,  7,  8,  9, 10],
               [11, 12, 13, 14, 15]]]]]]]]]])

In [27]:
arr.ndim

10

In [ ]:
arr

array([[[[[[[[[[ 1,  2,  3,  4,  5],
               [ 6,  7,  8,  9, 10],
               [11, 12, 13, 14, 15]]]]]]]]]])

* Shape - It tells about the size of the array

In [30]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [31]:
arr.shape

# (3,5)
# (5,3)

(3, 5)

In [ ]:
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])

In [ ]:
arr.shape

# (2,2,4)
# (2,4,2)

(2, 2, 4)

In [ ]:
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ],ndmin=20)

In [ ]:
arr.shape

# (10,2,4)


(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 4)

In [ ]:
arr

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4],
                         [5, 6, 7, 8]],

                        [[8, 7, 6, 5],
                         [4, 3, 2, 1]]]]]]]]]]]]]]]]]]]])

# dtype - It tells about the type of the data

In [35]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ], dtype='S')

# arr = np.array(["apple","mangoes","cherry",9.9])

In [36]:
arr.dtype

dtype('S2')

In [38]:
arr = np.array([
                ["1",2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [39]:
arr.dtype

dtype('<U11')

In [ ]:
arr.dtype

#  i - integer
#  s - string
#  b - boolean
#  c - complex
#  f - float

dtype('int64')

In [ ]:
arr.dtype

dtype('int16')

In [40]:
arr

array([['1', '2', '3', '4', '5'],
       ['6', '7', '8', '9', '10'],
       ['11', '12', '13', '14', '15']], dtype='<U11')

# size - It tells us the total number of elements

In [41]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.size

15

In [ ]:
np.size(ndarray,1(row)|0(column))

In [ ]:
np.size(arr,0)

3

In [ ]:
arr.size

In [ ]:
np.size(arr,1)

5

# Itemsize - It tells us about the length of the single element in bytes

In [45]:
arr = np.array([
                ['1',2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [48]:
arr = np.array(4)

In [46]:
arr.itemsize

44

# nbytes - Total bytes

In [49]:
arr.nbytes

4